export const TASK_EVENTS_CONSUMER_SQS_QUEUE_NAME = Symbol(
  'TASK_EVENTS_CONSUMER_SQS_QUEUE_NAME',
);
export const TASK_EVENTS_CONSUMER_SQS_QUEUE_URL = Symbol(
  'TASK_EVENTS_CONSUMER_SQS_QUEUE_URL',
);
